version: '3.8'

services:
  # API приложение
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://wildfire_user:wildfire_pass@postgres:5432/wildfire_db
      - REDIS_URL=redis://redis:6379/0
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MINIO_ENDPOINT=minio:9000

    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - services_default

  # Celery worker
  worker:
    build: .
    command: python run_worker.py
    environment:
      - DATABASE_URL=postgresql://wildfire_user:wildfire_pass@postgres:5432/wildfire_db
      - REDIS_URL=redis://redis:6379/0
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MINIO_ENDPOINT=minio:9000
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - services_default

networks:
  services_default:
    external: true
